[package]
name = "catppuccin-egui"
version = "1.0.1"
authors = ["Sam Nystrom <samuel.l.nystrom@gmail.com>"]
edition = "2021"
description = "Soothing pastel theme for egui."
documentation = "https://docs.rs/catppuccin-egui"
readme = "README.md"
homepage = "https://github.com/catpuccin/egui"
repository = "https://github.com/catpuccin/egui"
license = "MIT"
keywords = ["egui", "catppuccin", "theme", "gui"]
categories = ["gui"]
exclude = ["assets/"]

[dependencies]
egui = "0.20"

[dev-dependencies]
eframe = "0.20"
