[package]
name = "todo"
version = "5.6.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
eframe = "0.31"
catppuccin-egui = { version = "5.5", default-features = false, features = ["egui31"] }
