name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  Check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Check formatting
        run: cargo fmt --check
      - name: Run Clippy
        run: cargo clippy -- -D warnings

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test

  Publish:
    runs-on: ubuntu-latest
    environment: crates.io
    needs:
      - Check
      - Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-workspaces
        run: cargo install cargo-workspaces
      - name: Publish crates
        run: cargo ws publish -y --from-git --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
